### ISSUE TITLE
Fails to install in OSX

### ISSUE THREAD

**Issue by alesch** [awatson1978/starrynight#55]
The culprit is `sync-prompt`, a dependency from `Meteor-mrtbulkrelease`.
There are issues already created on both projects.
I'm creating this issue to track it, and save some time for the next developer.

Is it possible to avoid this dependency, or break it apart for some of the commands? I guess testing does not need it, right?

https://github.com/raix/Meteor-mrtbulkrelease/issues/1#issuecomment-117081874
https://github.com/shovon/sync-prompt/issues/15

**Comment by awatson1978** [comment]
Hmm.  That's too bad. The bulk-release functionality would be nice to have in there.  But if there are issues in both repos, maybe we should take it out, and focus on the testing story.  (Once testing is worked out, the testing story becomes a refactoring and package publication story.  Which is why it got included in the first place.)

Let me think on this.  My gut instinct is to maybe move it to a devDependency, so we can toggle on/off experimental features.  

http://stackoverflow.com/questions/9268259/how-do-you-install-development-only-npm-modules-for-node-js-package-json

**Comment by awatson1978** [comment]
I think we just fixed this, as of 3.2.62
Try 'npm update starrynight' and see if it works now.

**Comment by alesch** [comment]
YESSSSS, good job!
